# Welcome to Jekyll!

title: Home
email: kenjy.koan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Site personnel et partage de projets
baseurl: "" # the subpath of your site, e.g. /blog
url: https://kenjykoan.github.io/"" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: KenjyK
github_username:  kenjykoan
github: [metadata]

# Build settings
markdown: kramdown

# Build settings
#theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.26.1"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-feed
  - jekyll-include-cache

include: ["_pages", "_data", "_reminders", "_layouts", "_teachings"]

collections:
  reminders:
    output: true
    permalink: /:collection/:path/
  teachings:
    output: true
    permalink: /:collection/:path/

# default configurations for each type
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      comments: true
      share: true
      author_profile: true
      classes: wide

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  # _reminders
  - scope:
      path: ""
      type: reminders
    values:
      layout: single
      author_profile: true
      share: false
      output: true
      toc: true
      toc_label: "Contents"
      toc_icon: "swatchbook"
      sidebar: main
      classes: wide
      usemathjax: true

  # _teachings
  - scope:
      path: ""
      type: teachings
    values:
      layout: single
      author_profile: true
      share: false
      output: true
      toc: true
      toc_label: "Contents"
      toc_icon: "swatchbook"
      sidebar: main
      classes: wide
      usemathjax: true


author:
  name: "Kenjy KOAN"
  avatar: #
  bio: "Data Analyst Supply Chain" # Note: Markdown is allowed
  location: "Hauts-de-Seine, France"
  email            : "kenjy.koan@gmail.com"
  uri              :
  home             : # null (default), "absolute or relative url to link to author home"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "kenjykoan"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : #"tanguy_lef"
  lastfm           :
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          : # maybe...


# Site
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
